apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prod: HA replica counts, pinned :stable image tags, prod resource bump.
resources:
  - ../../base

labels:
  - pairs:
      environment: prod
    includeSelectors: false

replicas:
  - name: movieverse-backend
    count: 3
  - name: movieverse-frontend
    count: 2

images:
  - name: movieverse-backend
    newTag: stable
  - name: movieverse-frontend
    newTag: stable

patches:
  - target:
      kind: Deployment
      name: movieverse-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
